# Ejercicios de matrices

In [1]:
# Generating a matrix
a = matrix(c(1,3,5,7), ncol=2, nrow=2)

In [3]:
a

[,1] [,2]
[1,] 1    5   
[2,] 3    7

In [5]:
# Generating b matrix
b = matrix(c(2,4,6,8), ncol=2, nrow=2)

In [39]:
b

[,1] [,2]
[1,] 2    6   
[2,] 4    8

In [51]:
# Generating c matrix
c = matrix(c(2,4,6,8,5,9), ncol=3, nrow=2)

In [52]:
c

[,1] [,2] [,3]
[1,] 2    6    5   
[2,] 4    8    9

In [27]:
# Simply multiply matrix
a*b

[,1] [,2]
[1,]  2   30  
[2,] 12   56

In [28]:
# Multiply matrix
a %*% b

[,1] [,2]
[1,] 22   46  
[2,] 34   74

In [33]:
# Escriba una funci´on que toma 2 matrices A y B, y que devuelva TRUE si se puede calcular
# el producto AB.
is_multiply_matrix <- function(a,b){
    result = a %*% b
    return (!is.null(result))
}

In [34]:
is_multiply_matrix(a,b)

[1] TRUE

In [37]:
# Escriba una funci´on que toma 1 matriz A (cuadrada) y un entero n, y que devuelva la
# matriz A elevada a la potencia n.
pow_matrix <- function(matrix,n){
    return (matrix ^ n)
}

In [38]:
pow_matrix(a,2)

[,1] [,2]
[1,] 1    25  
[2,] 9    49

In [46]:
# Return a custom error if its not possible multiply matrix
is_multiply_or_error <- function(matrixa, matrixb){
    out <- tryCatch(
        {
            return (matrixa %*% matrixb)
        },
        error=function(cond) {
            message("An error ocurred")
#             message("Here's the original error message:")
#             message(cond)
            return(NA)
        }
    )    
}

# matrix A and C are not compatible
is_multiply_or_error(a,c)

An error ocurred



In [53]:
#  Escriba una funci´on sumCol que toma 1 matriz A, y que devuelva un vector cuyo elemento
# i sea la suma de elementos de la columna i de A.
sumCol <- function(matrix){
    return (colSums(matrix))
}

sumCol(a)
sumCol(b)
sumCol(c)

[1]  4 12

[1]  6 14

[1]  6 14 14